
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  server:
    image: my-simple-server:0.0.1
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGO_DB_URI: mongodb://root:example@mongo:27017/

volumes:
  mongo-data:
    driver: local
 