services: 
  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      MONGO_DB_URI: mongodb://root:example@database:27017/
      CORS_ORIGIN: http://localhost:8080
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
        - server
    ports:
      - 8080:80
    environment:
      REACT_APP_SERVER_URL: http://localhost:3000
volumes:
  mongo-data:
    driver: local